### subscribe
POST http://localhost:8000/topics/testcricket1/subscribe
content-type: application/json

{ "email": "golos60279@art2427.com" }

### publish
POST http://localhost:8000/topics/testcricket1/publish
content-type: application/json

{ "message": "India won" }

### list all topics
GET http://localhost:8000/topics

### list all topics with search query
GET http://localhost:8000/topics?search=cricket