### subscribe
POST http://localhost:8000/topics/cricket/subscribe
content-type: application/json

{ "email": "tempmail1@mail.com" }

### publish
POST http://localhost:8000/topics/cricket/publish
content-type: application/json

{ "message": "test match" }

### publish html
POST http://localhost:8000/topics/testcricket1/publish
content-type: application/json

{ "message": "<H1>I am normal</H1>" }

### list all topics
GET http://localhost:8000/topics

### list all topics with topics filter
GET http://localhost:8000/topics
Content-Type: application/json

{
  "filters": {
    "topics": ["cricket", "dance"]
  }
}

### list all topics with subscribers filter
GET http://localhost:8000/topics
Content-Type: application/json

{
  "filters": {
    "subscribers": ["tempmail1@mail.com"]
  }
}

### list all topics with subscribers filter and search filter
GET http://localhost:8000/topics?search=contemporary
Content-Type: application/json

{
  "filters": {
    "subscribers": ["tempmail1@mail.com"]
  }
}