### subscribe
POST http://localhost:8000/topics/cricket/subscribe
content-type: application/json

{ "email": "tempmail1@mail.com" }

### publish
POST http://localhost:8000/topics/cricket/publish
content-type: application/json

{ "message": "test match" }

### publish html
POST http://localhost:8000/topics/testcricket1/publish
content-type: application/json

{ "message": "<H1>I am normal</H1>" }

### list all topics
GET http://localhost:8000/topics

### list all topics with search filter
GET http://localhost:8000/topics?search=shubham.b.sharma@gmail.com